Repository amsul/pickadate.js, pull requests merged in 2018-02, with the labels that each got.

#859 Proper button rendering in IE8
  lib/picker.js
Labels: todo

#1052 Update vi_VN.js
  lib/translations/vi_VN.js
Labels: i18n

#953 update Chinese translation
  lib/translations/zh_CN.js
Labels: i18n

#1009 Update es_ES and minified
  lib/translations/es_ES.js
Labels: i18n

#1024 add Khmer translation (km_KH)
  lib/translations/km_KH.js
Labels: i18n

#997 suppress outline on the root picker element
  lib/themes-source/base.less
Labels: bug

#1034 Prevent Chrome 62 autofill from closing the picker
  lib/picker.js
Labels: bug

#1053 fix #841
  lib/picker.js
Labels: bug

#995 Allow 0 for min and max options
  lib/picker.date.js
Labels: bug

#943 Prevent paint when hidden
  lib/themes/classic.css
Labels: bug
